// <auto-generated />
using System;
using AmbulanceWPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmbulanceWPF.Migrations
{
    [DbContext(typeof(AmbulanceDbContext))]
    partial class AmbulanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AmbulanceWPF.Models.Diagnosis", b =>
                {
                    b.Property<string>("PatientJMB")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("DiseaseCode")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasColumnOrder(3);

                    b.Property<string>("DoctorJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorOpinion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeJMB")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientJMB", "DiseaseCode", "Date");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Diagnosis_Date");

                    b.HasIndex("DiseaseCode")
                        .HasDatabaseName("IX_Diagnosis_DiseaseCode");

                    b.HasIndex("DoctorJMB");

                    b.HasIndex("EmployeeJMB");

                    b.HasIndex("ExaminationId")
                        .HasDatabaseName("IX_Diagnosis_ExaminationId");

                    b.HasIndex("PatientJMB")
                        .HasDatabaseName("IX_Diagnosis_PatientJMB");

                    b.ToTable("Diagnosis", (string)null);

                    b.HasData(
                        new
                        {
                            PatientJMB = "5729618430725",
                            DiseaseCode = 1001,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorJMB = "6482157394021",
                            DoctorOpinion = "Stage 1 hypertension; monitor BP.",
                            ExaminationId = 1
                        },
                        new
                        {
                            PatientJMB = "4185270936518",
                            DiseaseCode = 1002,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorJMB = "6482157394021",
                            DoctorOpinion = "Likely viral origin.",
                            ExaminationId = 2
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.DiseaseCatalog", b =>
                {
                    b.Property<int>("DiseaseCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATE");

                    b.HasKey("DiseaseCode");

                    b.ToTable("DiseaseCatalog", (string)null);

                    b.HasData(
                        new
                        {
                            DiseaseCode = 1001,
                            Description = "Persistent high arterial blood pressure.",
                            DiseaseName = "Hypertension",
                            UpdateDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DiseaseCode = 1002,
                            Description = "Inflammation of the bronchial tubes, often viral.",
                            DiseaseName = "Acute bronchitis",
                            UpdateDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Employee", b =>
                {
                    b.Property<string>("JMB")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("JMB");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            JMB = "6482157394021",
                            IsActive = 1,
                            LastName = "Kovacevic",
                            Name = "Amar",
                            Password = "amarovasifra",
                            PasswordHash = "amarovasifra",
                            PhoneNumber = "+38761111222",
                            Role = "Doctor",
                            Theme = "Light",
                            Username = "amar.k"
                        },
                        new
                        {
                            JMB = "9035172846109",
                            IsActive = 1,
                            LastName = "Juric",
                            Name = "Mila",
                            Password = "milinasifra",
                            PasswordHash = "amarovasifra",
                            Role = "MedicalTechnician",
                            Theme = "Dark",
                            Username = "mila.j"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Examination", b =>
                {
                    b.Property<int>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExaminationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ExaminationDescription")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientJMB1")
                        .HasColumnType("TEXT");

                    b.HasKey("ExaminationId");

                    b.HasIndex("DoctorJMB")
                        .HasDatabaseName("IX_Examination_DoctorJMB");

                    b.HasIndex("ExaminationDate")
                        .HasDatabaseName("IX_Examination_Date");

                    b.HasIndex("PatientJMB")
                        .HasDatabaseName("IX_Examination_PatientJMB");

                    b.HasIndex("PatientJMB1");

                    b.ToTable("Examination", (string)null);

                    b.HasData(
                        new
                        {
                            ExaminationId = 1,
                            DoctorJMB = "6482157394021",
                            ExaminationDate = new DateTime(2025, 4, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ExaminationDescription = "Routine checkup",
                            PatientJMB = "5729618430725"
                        },
                        new
                        {
                            ExaminationId = 2,
                            DoctorJMB = "6482157394021",
                            ExaminationDate = new DateTime(2025, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExaminationDescription = "Cough and wheezing",
                            PatientJMB = "4185270936518"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Intervention", b =>
                {
                    b.Property<int>("InterventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("InterventionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("InterventionId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Intervention_Date");

                    b.HasIndex("PatientJMB")
                        .HasDatabaseName("IX_Intervention_PatientJMB");

                    b.ToTable("Intervention", (string)null);

                    b.HasData(
                        new
                        {
                            InterventionId = 1,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InterventionDescription = "Nebulization therapy administered.",
                            PatientJMB = "4185270936518"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.InterventionDoctor", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("DoctorJMB")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InterventionId", "DoctorJMB");

                    b.HasIndex("DoctorJMB")
                        .HasDatabaseName("IX_InterventionDoctor_DoctorJMB");

                    b.HasIndex("InterventionId")
                        .HasDatabaseName("IX_InterventionDoctor_InterventionId");

                    b.ToTable("InterventionDoctor", (string)null);

                    b.HasData(
                        new
                        {
                            InterventionId = 1,
                            DoctorJMB = "6482157394021",
                            Role = "Lead Doctor"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Location", b =>
                {
                    b.Property<int>("PostalCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("PostalCode");

                    b.ToTable("Location", (string)null);

                    b.HasData(
                        new
                        {
                            PostalCode = 71000,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            PostalCode = 78000,
                            Name = "Banja Luka"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicalRecord", b =>
                {
                    b.Property<string>("PatientJMB")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Insurance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientJMB");

                    b.HasIndex("DoctorJMB")
                        .HasDatabaseName("IX_MedicalRecord_DoctorJMB");

                    b.HasIndex("PatientJMB")
                        .HasDatabaseName("IX_MedicalRecord_PatientJMB");

                    b.ToTable("MedicalRecord", (string)null);

                    b.HasData(
                        new
                        {
                            PatientJMB = "5729618430725",
                            DoctorJMB = "6482157394021",
                            Gender = 0,
                            Insurance = 0,
                            MaritalStatus = "Single",
                            ParentName = "Marko"
                        },
                        new
                        {
                            PatientJMB = "4185270936518",
                            DoctorJMB = "6482157394021",
                            Gender = 1,
                            Insurance = 0,
                            MaritalStatus = "Married",
                            ParentName = "Ivana"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationCatalog", b =>
                {
                    b.Property<int>("MedicationCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("MedicationCode");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MedicationCatalog_IsActive");

                    b.HasIndex("Manufacturer")
                        .HasDatabaseName("IX_MedicationCatalog_Manufacturer");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_MedicationCatalog_Name");

                    b.ToTable("MedicationCatalog", (string)null);

                    b.HasData(
                        new
                        {
                            MedicationCode = 2001,
                            IsActive = true,
                            Manufacturer = "ACME Pharma",
                            Name = "Lisinopril"
                        },
                        new
                        {
                            MedicationCode = 2002,
                            IsActive = true,
                            Manufacturer = "BreatheWell",
                            Name = "Salbutamol"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationInventory", b =>
                {
                    b.Property<int>("MedicationCode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("MedicationCode");

                    b.ToTable("MedicationInventory", (string)null);

                    b.HasData(
                        new
                        {
                            MedicationCode = 2001,
                            Quantity = 25m
                        },
                        new
                        {
                            MedicationCode = 2002,
                            Quantity = 40m
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationItem", b =>
                {
                    b.Property<int>("MedicationCode")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("ProcurementId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicationCode", "ProcurementId");

                    b.HasIndex("MedicationCode")
                        .HasDatabaseName("IX_MedicationItem_MedicationCode");

                    b.HasIndex("ProcurementId")
                        .HasDatabaseName("IX_MedicationItem_ProcurementId");

                    b.ToTable("MedicationItem", (string)null);

                    b.HasData(
                        new
                        {
                            MedicationCode = 2001,
                            ProcurementId = 1,
                            Quantity = 50
                        },
                        new
                        {
                            MedicationCode = 2002,
                            ProcurementId = 2,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Patient", b =>
                {
                    b.Property<string>("JMB")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("JMB");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DateOfBirth");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Gender");

                    b.Property<bool>("Insurance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Insurance");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JMB");

                    b.HasIndex("ResidenceLocationId")
                        .HasDatabaseName("IX_Patient_ResidenceLocationId");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            JMB = "5729618430725",
                            Allergies = "",
                            DateOfBirth = "12/07/2001",
                            Gender = false,
                            Insurance = true,
                            LastName = "Horvat",
                            Name = "Ivan",
                            ResidenceLocationId = 71000
                        },
                        new
                        {
                            JMB = "4185270936518",
                            Allergies = "",
                            DateOfBirth = "28/02/1995",
                            Gender = true,
                            Insurance = true,
                            LastName = "Petrovic",
                            Name = "Sara",
                            ResidenceLocationId = 78000
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Phone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Phone", (string)null);

                    b.HasData(
                        new
                        {
                            PhoneNumber = "+38761111222"
                        },
                        new
                        {
                            PhoneNumber = "+38762123456"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Procurement", b =>
                {
                    b.Property<int>("ProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcurementDate")
                        .HasColumnType("DATE");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("ProcurementId");

                    b.HasIndex("ProcurementDate")
                        .HasDatabaseName("IX_Procurement_Date");

                    b.ToTable("Procurement", (string)null);

                    b.HasData(
                        new
                        {
                            ProcurementId = 1,
                            ProcurementDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcurementId = 2,
                            ProcurementDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Referral", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.Property<int>("DiseaseCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorJMB")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientJMB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialists")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("ReferralId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Referral_Date");

                    b.HasIndex("DiseaseCode")
                        .HasDatabaseName("IX_Referral_DiseaseCode");

                    b.HasIndex("DoctorJMB")
                        .HasDatabaseName("IX_Referral_DoctorJMB");

                    b.HasIndex("ExaminationId")
                        .HasDatabaseName("IX_Referral_ExaminationId");

                    b.HasIndex("PatientJMB");

                    b.ToTable("Referral", (string)null);

                    b.HasData(
                        new
                        {
                            ReferralId = 1,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiseaseCode = 1002,
                            DoctorJMB = "6482157394021",
                            ExaminationId = 2,
                            PatientJMB = "4185270936518",
                            Specialists = "Pulmonologist"
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Therapy", b =>
                {
                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("MedicationCode")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<decimal?>("Dosage")
                        .HasColumnType("REAL");

                    b.HasKey("InterventionId", "MedicationCode");

                    b.HasIndex("InterventionId")
                        .HasDatabaseName("IX_Therapy_InterventionId");

                    b.HasIndex("MedicationCode")
                        .HasDatabaseName("IX_Therapy_MedicationCode");

                    b.ToTable("Therapy", (string)null);

                    b.HasData(
                        new
                        {
                            InterventionId = 1,
                            MedicationCode = 2002,
                            Dosage = 2.5m
                        });
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Diagnosis", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.DiseaseCatalog", "Disease")
                        .WithMany("Diagnosis")
                        .HasForeignKey("DiseaseCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("DoctorJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Employee", null)
                        .WithMany("Diagnosis")
                        .HasForeignKey("EmployeeJMB");

                    b.HasOne("AmbulanceWPF.Models.Examination", "Examination")
                        .WithMany("Diagnosis")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Employee");

                    b.Navigation("Examination");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Employee", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Phone", "Phone")
                        .WithMany("Employees")
                        .HasForeignKey("PhoneNumber")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Examination", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Employee", "Employee")
                        .WithMany("Examinations")
                        .HasForeignKey("DoctorJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Examinations")
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Patient", null)
                        .WithMany("Examinations")
                        .HasForeignKey("PatientJMB1");

                    b.Navigation("Employee");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Intervention", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.InterventionDoctor", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Employee", "Employee")
                        .WithMany("InterventionDoctors")
                        .HasForeignKey("DoctorJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Intervention", "Intervention")
                        .WithMany("InterventionDoctors")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicalRecord", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Employee", "Employee")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Patient", "Patient")
                        .WithOne()
                        .HasForeignKey("AmbulanceWPF.Models.MedicalRecord", "PatientJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationInventory", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.MedicationCatalog", "Medication")
                        .WithOne("MedicationInventory")
                        .HasForeignKey("AmbulanceWPF.Models.MedicationInventory", "MedicationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationItem", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.MedicationCatalog", "Medication")
                        .WithMany("MedicationItems")
                        .HasForeignKey("MedicationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Procurement", "Procurement")
                        .WithMany("MedicationItems")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Patient", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Location", "ResidenceLocation")
                        .WithMany()
                        .HasForeignKey("ResidenceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidenceLocation");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Referral", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.DiseaseCatalog", "Disease")
                        .WithMany()
                        .HasForeignKey("DiseaseCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Employee", "Employee")
                        .WithMany("Referrals")
                        .HasForeignKey("DoctorJMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.Examination", "Examination")
                        .WithMany("Referrals")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Referrals")
                        .HasForeignKey("PatientJMB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Employee");

                    b.Navigation("Examination");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Therapy", b =>
                {
                    b.HasOne("AmbulanceWPF.Models.Intervention", "Intervention")
                        .WithMany("Therapies")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmbulanceWPF.Models.MedicationCatalog", "Medication")
                        .WithMany("Therapies")
                        .HasForeignKey("MedicationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.DiseaseCatalog", b =>
                {
                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Employee", b =>
                {
                    b.Navigation("Diagnosis");

                    b.Navigation("Examinations");

                    b.Navigation("InterventionDoctors");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Examination", b =>
                {
                    b.Navigation("Diagnosis");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Intervention", b =>
                {
                    b.Navigation("InterventionDoctors");

                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicalRecord", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("Examinations");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.MedicationCatalog", b =>
                {
                    b.Navigation("MedicationInventory")
                        .IsRequired();

                    b.Navigation("MedicationItems");

                    b.Navigation("Therapies");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Patient", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Phone", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AmbulanceWPF.Models.Procurement", b =>
                {
                    b.Navigation("MedicationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
